version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - 8080:8080
    environment:
      - MODE=json-rpc #supported modes: json-rpc, native, normal
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli"
    restart: always

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - "./db-data:/var/lib/postgresql/data"

  bot:
    image: signal-community-bot:latest
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASS}
      - DB_PORT=5432
      - SIGNAL_HOST=signal-cli-rest-api:8080
      - DB_NAME=signal_community_bot
      - PHONE_NUMBER=${PHONE_NUMBER}
    links:
      - db
      - signal-cli-rest-api

